### ISSUE TITLE
Inconsistent code formatting

### ISSUE THREAD

**Issue by AaronDSmit** [BrentKingma/PowerfulItems#5]
I noticed some inconsistent formatting, I suggest using Ctrl + K + D in Visual studio to format your code

![Screenshot 2021-05-31 171524](https://user-images.githubusercontent.com/26218130/120155037-cfc75580-c233-11eb-8718-603e250be040.png)

**Comment by AaronDSmit** [comment]
Oh also I noticed you don't use else if, is there an intentional reason for that?

**Comment by BrentKingma** [comment]
no particular reason

**Comment by BrentKingma** [comment]
Corrected code format.
